import { z } from "zod";

const channelSchema = z.object({
    id: z.string(),
    type: z.number(),
    guild_id: z.string().optional(),
    position: z.number().optional(),
    permission_overwrites: z.array(z.object({})).optional(),
    name: z.string().nullable().optional(),
    topic: z.string().nullable().optional(),
    nsfw: z.boolean().optional(),
    last_message_id: z.unknown().optional(),
    bitrate: z.number().optional(),
    user_limit: z.number().optional(),
    rate_limit_per_user: z.number().optional(),
    recipients: z.array(z.object({})).optional(),
    icon: z.string().nullable().optional(),
    owner_id: z.string().optional(),
    application_id: z.string().optional(),
    parent_id: z.unknown().optional(),
    last_pin_timestamp: z.unknown().optional(),
    rtc_region: z.string().nullable().optional(),
    video_quality_mode: z.number().optional(),
    message_count: z.number().optional(),
    member_count: z.number().optional(),
    thread_metadata: z.unknown().optional(),
    member: z.unknown().optional(),
    default_auto_archive_duration: z.number().optional(),
    permissions: z.string().optional(),
    flags: z.number().optional(),
    total_message_sent: z.number().optional(),
    available_tags: z.array(z.object({})).optional(),
    applied_tags: z.array(z.string()).optional(),
    default_reaction_emoji: z.unknown().optional(),
    default_thread_rate_limit_per_user: z.number().optional(),
    default_sort_order: z.unknown().optional(),
    default_forum_layout: z.number().optional(),
});
