CREATE TABLE guild_settings (
    guild_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    command_prefix VARCHAR(16) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
