CREATE TABLE custom_commands (
    guild_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(32) NOT NULL,
    response VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (guild_id, name)
);
