/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard.index'
import { Route as DashboardAdminRouteImport } from './routes/_dashboard.admin'
import { Route as DashboardAdminIndexRouteImport } from './routes/_dashboard.admin.index'
import { Route as DashboardGuildsGuildIdRouteImport } from './routes/_dashboard.guilds.$guildId'
import { Route as InstallDiscordErrorRouteImport } from './routes/install.discord.error'
import { Route as InstallDiscordSuccessRouteImport } from './routes/install.discord.success'
import { Route as DashboardGuildsGuildIdModerationRouteImport } from './routes/_dashboard.guilds.$guildId_.moderation'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardGuildsGuildIdRoute = DashboardGuildsGuildIdRouteImport.update({
  id: '/guilds/$guildId',
  path: '/guilds/$guildId',
  getParentRoute: () => DashboardRoute,
} as any)
const InstallDiscordErrorRoute = InstallDiscordErrorRouteImport.update({
  id: '/install/discord/error',
  path: '/install/discord/error',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallDiscordSuccessRoute = InstallDiscordSuccessRouteImport.update({
  id: '/install/discord/success',
  path: '/install/discord/success',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGuildsGuildIdModerationRoute =
  DashboardGuildsGuildIdModerationRouteImport.update({
    id: '/guilds/$guildId_/moderation',
    path: '/guilds/$guildId/moderation',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof DashboardAdminRouteWithChildren
  '/guilds/$guildId': typeof DashboardGuildsGuildIdRoute
  '/install/discord/error': typeof InstallDiscordErrorRoute
  '/install/discord/success': typeof InstallDiscordSuccessRoute
  '/admin/': typeof DashboardAdminIndexRoute
  '/guilds/$guildId/moderation': typeof DashboardGuildsGuildIdModerationRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof DashboardIndexRoute
  '/guilds/$guildId': typeof DashboardGuildsGuildIdRoute
  '/install/discord/error': typeof InstallDiscordErrorRoute
  '/install/discord/success': typeof InstallDiscordSuccessRoute
  '/admin': typeof DashboardAdminIndexRoute
  '/guilds/$guildId/moderation': typeof DashboardGuildsGuildIdModerationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/guilds/$guildId': typeof DashboardGuildsGuildIdRoute
  '/install/discord/error': typeof InstallDiscordErrorRoute
  '/install/discord/success': typeof InstallDiscordSuccessRoute
  '/_dashboard/admin/': typeof DashboardAdminIndexRoute
  '/_dashboard/guilds/$guildId_/moderation': typeof DashboardGuildsGuildIdModerationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/guilds/$guildId'
    | '/install/discord/error'
    | '/install/discord/success'
    | '/admin/'
    | '/guilds/$guildId/moderation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/guilds/$guildId'
    | '/install/discord/error'
    | '/install/discord/success'
    | '/admin'
    | '/guilds/$guildId/moderation'
  id:
    | '__root__'
    | '/_dashboard'
    | '/login'
    | '/_dashboard/admin'
    | '/_dashboard/'
    | '/_dashboard/guilds/$guildId'
    | '/install/discord/error'
    | '/install/discord/success'
    | '/_dashboard/admin/'
    | '/_dashboard/guilds/$guildId_/moderation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  InstallDiscordErrorRoute: typeof InstallDiscordErrorRoute
  InstallDiscordSuccessRoute: typeof InstallDiscordSuccessRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin': {
      id: '/_dashboard/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/': {
      id: '/_dashboard/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/guilds/$guildId': {
      id: '/_dashboard/guilds/$guildId'
      path: '/guilds/$guildId'
      fullPath: '/guilds/$guildId'
      preLoaderRoute: typeof DashboardGuildsGuildIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/install/discord/error': {
      id: '/install/discord/error'
      path: '/install/discord/error'
      fullPath: '/install/discord/error'
      preLoaderRoute: typeof InstallDiscordErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install/discord/success': {
      id: '/install/discord/success'
      path: '/install/discord/success'
      fullPath: '/install/discord/success'
      preLoaderRoute: typeof InstallDiscordSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/guilds/$guildId_/moderation': {
      id: '/_dashboard/guilds/$guildId_/moderation'
      path: '/guilds/$guildId/moderation'
      fullPath: '/guilds/$guildId/moderation'
      preLoaderRoute: typeof DashboardGuildsGuildIdModerationRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardGuildsGuildIdRoute: typeof DashboardGuildsGuildIdRoute
  DashboardGuildsGuildIdModerationRoute: typeof DashboardGuildsGuildIdModerationRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardGuildsGuildIdRoute: DashboardGuildsGuildIdRoute,
  DashboardGuildsGuildIdModerationRoute: DashboardGuildsGuildIdModerationRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  InstallDiscordErrorRoute: InstallDiscordErrorRoute,
  InstallDiscordSuccessRoute: InstallDiscordSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
