[workspace]
resolver = "3"
members = [
    "crates/api",
    "crates/bot",
    "crates/bot-core",
    "crates/database",
    "crates/feature-admin",
    "crates/feature-endfield",
    "crates/feature-info",
    "crates/feature-settings",
    "crates/migrate",
]

[workspace.dependencies]
api = { path = "crates/api" }
bot-core = { path = "crates/bot-core" }
database = { path = "crates/database" }
feature-admin = { path = "crates/feature-admin" }
feature-endfield = { path = "crates/feature-endfield" }
feature-info = { path = "crates/feature-info" }
feature-settings = { path = "crates/feature-settings" }

poise = "0.6.2"
axum = "0.8"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
sea-query = { version = "0.32", features = ["backend-mysql", "derive"] }
serde = { version = "1", features = ["derive"] }
serenity = "0.12.5"
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "mysql", "uuid", "chrono", "json", "migrate"] }
thiserror = "2"
tokio = { version = "1.52.3", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
uuid = { version = "1", features = ["v7"] }
