version: '3.8'

services:
  mysql:
    image: mysql:8.1.0
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: yin
      MYSQL_DATABASE: yin
      MYSQL_USER: yin
      MYSQL_PASSWORD: yin

volumes:
  mysql:
    driver: local