apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: yin
  labels:
    app: database 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
      annotations:
        linkerd.io/inject: enabled
        config.linkerd.io/skip-outbound-ports: "3306"
    spec:
      containers:
        - image: ctr.avrg.dev/yin/database:6954231103921411883c307ad34615ba1029b6bd
          name: database
          ports:
          - containerPort: 3000
            name: grpc
          - containerPort: 8080
            name: prometheus
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-url
                  key: url
            - name: YIN_WORKER_GRPC_HOST
              value: worker.yin:3000

            - name: YIN_DATABASE_GRPC_HOST
              value: 0.0.0.0:3000

            - name: YIN_DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-token
                  key: token

          # always pull because im lazy and just use latest for dev image
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100Mi"
              cpu: "0.1"
            limits:
              memory: "1Gi"
              cpu: "1"