apiVersion: v1
kind: ConfigMap
metadata:
  name: yin-config
  namespace: yin-dev
data:
  APP_ENV: development
  RUST_LOG: info
  DATABASE_URL: mysql://yin:yin@mariadb:3306/yin
  API_BIND_ADDR: 0.0.0.0:3000
  API_CORS_ALLOWED_ORIGINS: http://panel.yin.localhost,http://localhost:3000
  AUTH_SERVICE_URL: http://auth:3001
  API_SERVICE_URL: http://api:3000
  POSTHOG_HOST: https://eu.i.posthog.com
  POSTHOG_APP_HOST: https://eu.posthog.com
  AUTH_HOST: 0.0.0.0
  AUTH_PORT: "3001"
  BETTER_AUTH_URL: http://auth.yin.localhost
  AUTH_COOKIE_DOMAIN: yin.localhost
  AUTH_INSTALL_SUCCESS_URL: http://panel.yin.localhost/install/discord/success
  AUTH_INSTALL_ERROR_URL: http://panel.yin.localhost/install/discord/error
  DISCORD_BOT_PERMISSIONS: "0"
  AUTH_TRUSTED_ORIGINS: http://api.yin.localhost,http://auth.yin.localhost,http://panel.yin.localhost,http://localhost:3000
