apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: yin
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - image: ctr.avrg.dev/yin/gateway:5f11ff5c7c37ead93f7d374dbe65fd160d725635
          name: gateway
          ports:
          - containerPort: 8080
            name: prometheus
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-token
                  key: token

            - name: YIN_DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-token
                  key: token

            - name: K3S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: YIN_WORKER_GRPC_HOST
              value: worker.yin:3000
            - name: YIN_DATABASE_GRPC_HOST
              value: database.yin:3000
              
            - name: YIN_PROMETHEUS_PORT
              value: "8080"  
          # always pull because im lazy and just use latest for dev image
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100Mi"
              cpu: "0.1"
            limits:
              memory: "1Gi"
              cpu: "1"
