# https://raw.githubusercontent.com/AnswerOverflow/AnswerOverflow/main/.github/ISSUE_TEMPLATE/feature_request.yml
name: Feature request
description: Request a new feature 
labels: [⭐ enhancement]
body:  
  - type: dropdown
    id: package
    attributes:
      label: What is this for?
      options:
        - panel/api
        - bot
        - other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Feature
      description: A clear and concise description of what feature you want to be implemented.
      placeholder: As a [role]... I'd like [brief description] ... because [reason]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Ideal solution or implementation
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Other context
      description: Any other context, screenshots, or file uploads that help us understand your feature request.